"""empty message

Revision ID: e86fe2d6cafa
Revises: 
Create Date: 2023-05-14 06:26:27.990748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e86fe2d6cafa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('target', sa.String(length=10000), nullable=False),
    sa.Column('url_id', sa.String(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name=op.f('fk_urls_user_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_urls')),
    sa.UniqueConstraint('url_id', name=op.f('uq_urls_url_id'))
    )
    op.create_table('hits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('timezone_name', sa.String(), nullable=True),
    sa.Column('timezone_offset', sa.Integer(), nullable=True),
    sa.Column('timezone_id', sa.String(), nullable=True),
    sa.Column('timezone_abbrv', sa.String(), nullable=True),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.Column('location_city', sa.String(), nullable=True),
    sa.Column('location_postal', sa.String(), nullable=True),
    sa.Column('location_country_name', sa.String(), nullable=True),
    sa.Column('location_country_code', sa.String(), nullable=True),
    sa.Column('location_continent_name', sa.String(), nullable=True),
    sa.Column('location_continent_code', sa.String(), nullable=True),
    sa.Column('browser_name', sa.String(), nullable=True),
    sa.Column('browser_version', sa.String(), nullable=True),
    sa.Column('os_name', sa.String(), nullable=True),
    sa.Column('os_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['url'], ['urls.id'], name=op.f('fk_hits_url_urls')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hits'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hits')
    op.drop_table('urls')
    op.drop_table('users')
    # ### end Alembic commands ###
